name: Auto Publish NuGet on Push

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Directory.Packages.props"
      - "Directory.Build.props"
      - "nuget.config"
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: windows-latest

    env:
      CI_VERSION: 0.0.0-ci.${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore

      # Detect changed projects in this push
      - name: Detect changed projects
        id: changes
        shell: pwsh
        run: |
          $before = "${{ github.event.before }}"
          $after  = "${{ github.sha }}"
          if (-not $before) { $before = "$after^" }

          $changed = git diff --name-only $before $after | Where-Object { $_ -like "src/*" }
          $projSet = @{}

          foreach ($f in $changed) {
            $csproj = $null
            if ($f -match '\.csproj$') {
              $csproj = $f
            } else {
              $dir = Split-Path $f -Parent
              while ($dir -and -not (Test-Path (Join-Path $dir "*.csproj"))) {
                $parent = Split-Path $dir -Parent
                if ($parent -eq $dir) { break }
                $dir = $parent
              }
              if ($dir) {
                $found = Get-ChildItem -Path (Join-Path $dir "*.csproj") -ErrorAction SilentlyContinue | Select-Object -First 1
                if ($found) { $csproj = $found.FullName }
              }
            }

            if ($csproj -and ($csproj -notmatch '\.Tests\.csproj$')) {
              $projSet[$csproj] = $true
            }
          }

          if ($projSet.Keys.Count -eq 0) {
            "changed=none" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            $list = ($projSet.Keys | Sort-Object) -join "`n"
            "changed=$list" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Write-Host "Changed projects:`n$list"
          }

      - name: Skip if nothing to publish
        if: steps.changes.outputs.changed == 'none'
        run: echo "No packable project changes detected; skipping."

      - name: Build (Release)
        if: steps.changes.outputs.changed != 'none'
        run: dotnet build -c Release --no-restore

      - name: Pack changed projects
        if: steps.changes.outputs.changed != 'none'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          $projects = @()
          $projects = "${{ steps.changes.outputs.changed }}".Split("`n") | Where-Object { $_ -and $_.Trim() -ne "" }
          foreach ($p in $projects) {
            Write-Host "Packing: $p"
            dotnet pack "$p" -c Release -o artifacts --no-build /p:Version=${{ env.CI_VERSION }}
          }

      - name: Upload packages
        if: steps.changes.outputs.changed != 'none'
        uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: artifacts/*.nupkg

      - name: Upload symbols
        if: steps.changes.outputs.changed != 'none'
        uses: actions/upload-artifact@v4
        with:
          name: snupkgs
          path: artifacts/*.snupkg

      - name: Push to GitHub Packages
        if: steps.changes.outputs.changed != 'none'
        shell: pwsh
        run: |
          $source = "https://nuget.pkg.github.com/EagleViewEnt/index.json"
          Get-ChildItem artifacts -Filter *.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName --api-key ${{ secrets.GITHUB_TOKEN }} --source $source --skip-duplicate
          }
          Get-ChildItem artifacts -Filter *.snupkg | ForEach-Object {
            dotnet nuget push $_.FullName --api-key ${{ secrets.GITHUB_TOKEN }} --source $source --skip-duplicate
          }
